# Generated by Django 4.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('character', '人物设定'), ('system', '系统提示词'), ('template', '回复模板')], db_index=True, max_length=50, verbose_name='类别')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='唯一标识')),
                ('content', models.TextField(verbose_name='提示词内容')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否激活')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '提示词库',
                'verbose_name_plural': '提示词库',
                'db_table': 'prompt_library',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('memory_type', models.CharField(choices=[('hotspot', '热点话题'), ('user_memory', '用户记忆点'), ('important_event', '重要事件')], db_index=True, max_length=50, verbose_name='记忆类型')),
                ('strength', models.IntegerField(default=5, help_text='记忆强度 1-10', verbose_name='强度')),
                ('weight', models.FloatField(default=1.0, help_text='记忆权重，影响检索优先级', verbose_name='权重')),
                ('forget_time', models.DateTimeField(blank=True, help_text='超过此时间后记忆衰减', null=True, verbose_name='遗忘时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '记忆库',
                'verbose_name_plural': '记忆库',
                'db_table': 'memory_library',
                'ordering': ['-weight', '-strength', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlannedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('task_type', models.CharField(choices=[('daily', '日常任务'), ('special', '特殊任务'), ('reminder', '提醒任务')], db_index=True, max_length=50, verbose_name='任务类型')),
                ('scheduled_time', models.DateTimeField(db_index=True, verbose_name='计划时间')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('completed', '已完成'), ('cancelled', '已取消'), ('failed', '执行失败')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '计划任务',
                'verbose_name_plural': '计划任务',
                'db_table': 'planned_task',
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='ReplyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('user', '用户触发'), ('autonomous', '自主触发')], db_index=True, max_length=20, verbose_name='触发类型')),
                ('content', models.TextField(verbose_name='回复内容')),
                ('context', models.JSONField(blank=True, default=dict, help_text='AI决策时的上下文', verbose_name='上下文信息')),
                ('scheduled_time', models.DateTimeField(db_index=True, verbose_name='计划回复时间')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('executing', '执行中'), ('completed', '已完成'), ('failed', '执行失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': '回复任务',
                'verbose_name_plural': '回复任务',
                'db_table': 'reply_task',
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='MessageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('received', '接收消息'), ('sent', '发送消息')], db_index=True, max_length=20, verbose_name='消息类型')),
                ('sender', models.CharField(db_index=True, max_length=200, verbose_name='发送者')),
                ('receiver', models.CharField(db_index=True, max_length=200, verbose_name='接收者')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='消息时间')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='消息的原始JSON数据', verbose_name='原始数据')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('reply_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.replytask', verbose_name='关联回复任务')),
            ],
            options={
                'verbose_name': '消息记录',
                'verbose_name_plural': '消息记录',
                'db_table': 'message_record',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='promptlibrary',
            index=models.Index(fields=['category', 'is_active'], name='prompt_libr_categor_7f61ef_idx'),
        ),
        migrations.AddIndex(
            model_name='memorylibrary',
            index=models.Index(fields=['memory_type', '-weight'], name='memory_libr_memory__a7c99d_idx'),
        ),
        migrations.AddIndex(
            model_name='memorylibrary',
            index=models.Index(fields=['-created_at'], name='memory_libr_created_8b3c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='plannedtask',
            index=models.Index(fields=['status', 'scheduled_time'], name='planned_tas_status_0e67fc_idx'),
        ),
        migrations.AddIndex(
            model_name='replytask',
            index=models.Index(fields=['status', 'scheduled_time'], name='reply_task_status_0d2a55_idx'),
        ),
        migrations.AddIndex(
            model_name='replytask',
            index=models.Index(fields=['trigger_type', 'status'], name='reply_task_trigger_d56df6_idx'),
        ),
        migrations.AddIndex(
            model_name='messagerecord',
            index=models.Index(fields=['-timestamp'], name='message_rec_timesta_f1de33_idx'),
        ),
        migrations.AddIndex(
            model_name='messagerecord',
            index=models.Index(fields=['message_type', '-timestamp'], name='message_rec_message_e8b9aa_idx'),
        ),
        migrations.AddIndex(
            model_name='messagerecord',
            index=models.Index(fields=['sender', '-timestamp'], name='message_rec_sender_9c1c97_idx'),
        ),
    ]
