# Generated by Django 4.2.7 on 2025-12-09 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptlibrary',
            name='category',
            field=models.CharField(choices=[('character', '人物设定'), ('system', '系统提示词'), ('template', '回复模板'), ('reply_decision', '回复决策'), ('memory_detection', '记忆检测'), ('daily_planning', '每日计划'), ('autonomous_message', '自主消息'), ('hotspot_judge', '热点判断'), ('emotion_analysis', '情绪分析')], db_index=True, max_length=50, verbose_name='类别'),
        ),
        migrations.CreateModel(
            name='EmotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_type', models.CharField(choices=[('happy', '开心'), ('sad', '悲伤'), ('angry', '愤怒'), ('anxious', '焦虑'), ('calm', '平静'), ('excited', '兴奋'), ('tired', '疲倦'), ('neutral', '中性'), ('worried', '担忧'), ('grateful', '感激')], db_index=True, max_length=20, verbose_name='情绪类型')),
                ('intensity', models.IntegerField(default=5, help_text='情绪强度 1-10，10最强烈', verbose_name='情绪强度')),
                ('trigger_source', models.CharField(choices=[('user_message', '用户消息'), ('system', '系统判断'), ('time_decay', '时间衰减'), ('daily_init', '每日初始化')], db_index=True, max_length=20, verbose_name='触发来源')),
                ('trigger_content', models.TextField(blank=True, help_text='引发情绪变化的消息或事件', verbose_name='触发内容')),
                ('description', models.TextField(blank=True, help_text='AI对当前情绪状态的描述', verbose_name='情绪描述')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='存储额外信息，如情绪变化原因等', verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotions', to='core.chatuser', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '情绪记录',
                'verbose_name_plural': '情绪记录',
                'db_table': 'emotion_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='emotion_rec_user_id_7063b5_idx'), models.Index(fields=['emotion_type', '-created_at'], name='emotion_rec_emotion_e32d4e_idx'), models.Index(fields=['user', 'emotion_type'], name='emotion_rec_user_id_cf28e4_idx')],
            },
        ),
    ]
