# Generated by Django 4.2.7 on 2025-11-28 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='memorylibrary',
            new_name='memory_libr_memory__84a828_idx',
            old_name='memory_libr_memory__a7c99d_idx',
        ),
        migrations.RenameIndex(
            model_name='memorylibrary',
            new_name='memory_libr_created_753a19_idx',
            old_name='memory_libr_created_8b3c5a_idx',
        ),
        migrations.RenameIndex(
            model_name='messagerecord',
            new_name='message_rec_timesta_cd803b_idx',
            old_name='message_rec_timesta_f1de33_idx',
        ),
        migrations.RenameIndex(
            model_name='messagerecord',
            new_name='message_rec_message_061667_idx',
            old_name='message_rec_message_e8b9aa_idx',
        ),
        migrations.RenameIndex(
            model_name='messagerecord',
            new_name='message_rec_sender_af3a1f_idx',
            old_name='message_rec_sender_9c1c97_idx',
        ),
        migrations.RenameIndex(
            model_name='plannedtask',
            new_name='planned_tas_status_89b8a0_idx',
            old_name='planned_tas_status_0e67fc_idx',
        ),
        migrations.RenameIndex(
            model_name='promptlibrary',
            new_name='prompt_libr_categor_9163fd_idx',
            old_name='prompt_libr_categor_7f61ef_idx',
        ),
        migrations.RenameIndex(
            model_name='replytask',
            new_name='reply_task_status_fdf371_idx',
            old_name='reply_task_status_0d2a55_idx',
        ),
        migrations.RenameIndex(
            model_name='replytask',
            new_name='reply_task_trigger_37495f_idx',
            old_name='reply_task_trigger_d56df6_idx',
        ),
    ]
