# Generated by Django 4.2.7 on 2025-12-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_promptlibrary_category_emotionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='is_initialized',
            field=models.BooleanField(db_index=True, default=False, help_text='用户是否已完成引导流程（设定人物设定等）', verbose_name='是否已初始化'),
        ),
    ]
